# Generated by Django 3.1 on 2020-10-03 04:30

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.img_upload_function, verbose_name='Изобродение поста'),
        ),
    ]
